create sequence hibernate_sequence start 1 increment 1;
create table message (id int8 not null, team_id int8, string varchar(10000), filename varchar(1000), from_user boolean, primary key (id));
create table answer (id int8 not null, answers varchar(255), is_found boolean not null, page_id int8, page_game_id int8, primary key (id));
create table application (id int8 not null, date varchar(255), mail varchar(255), name varchar(255), number varchar(255), time varchar(255), primary key (id));
create table baner (id int8 not null, filename varchar(500), primary key (id));
create table element (id int8 not null, file_name varchar(500), is_image boolean not null, is_text boolean not null, is_video boolean not null, order_number int4 not null, string varchar(10000),  page_id int8, page_game_id int8, quest_id int8, primary key (id));
create table game (id int8 not null,pause_finish timestamp, pause_start timestamp, sum varchar(255) ,finish timestamp, is_finished boolean not null, is_paused boolean not null, is_started boolean not null, pause varchar(255), start timestamp, quest_id int8, team_id int8, primary key (id));
create table hint (id int8 not null, file_name varchar(500), is_image boolean not null, is_text boolean not null, is_video boolean not null, order_number int4 not null, string varchar(10000), time int4 not null, page_id int8, page_game_id int8, primary key (id));
create table page (id int8 not null, name varchar(255), order_number int4 not null, time float8 not null, quest_id int8, primary key (id));
create table page_game (id int8 not null,start timestamp,order_number_real varchar(255) , answer_time float8 not null, answered boolean not null, found_answers varchar(1000), name varchar(255), order_number varchar(255), time float8 not null, time_elapsed float8 not null, game_id int8, primary key (id));
create table quest (id int8 not null, description varchar(10000), filename varchar(500), filename_small varchar(500), name varchar(500), place varchar(255), short_description varchar(10000), primary key (id));
create table team (id int8 not null,date_string varchar(255) ,cap_name varchar(255), cap_number varchar(255), code varchar(255), number_of_players varchar(255), second_cap_name varchar(255), second_cap_number varchar(255), team_name varchar(255), quest_id int8, is_checked_user boolean, is_checked boolean, primary key (id));
create table user_role (user_id int8 not null, roles varchar(255));
create table usr (id int8 not null, activation_code varchar(255), active boolean not null, email varchar(255), password varchar(255), username varchar(255), primary key (id));
alter table if exists answer add constraint FKlj9ipyu6juia1cxo8jcblgg5s foreign key (page_id) references page;
alter table if exists answer add constraint FKatvpmgk68hte4rt9jnjd7rnrn foreign key (page_game_id) references page_game;
alter table if exists element add constraint FKke6xqc7m3l010f610dldu4hvi foreign key (page_id) references page;
alter table if exists element add constraint FKbqsn9mhrq3red689o316rn755 foreign key (page_game_id) references page_game;
alter table if exists element add constraint FK89fj6b7fdcdn4m2f7qnh9wjcm foreign key (quest_id) references quest;
alter table if exists game add constraint FKg8857rr7h2arqxa28y42kj3lo foreign key (quest_id) references quest;
alter table if exists game add constraint FK1gq3iavetstsxyuqd92o5e6lj foreign key (team_id) references team;
alter table if exists hint add constraint FK3bg18pubnnho5by9ufikapjcx foreign key (page_id) references page;
alter table if exists hint add constraint FKhphw6acj34niela8yxx9pbdsu foreign key (page_game_id) references page_game;
alter table if exists page add constraint FKe12ev7yobkoibhtn4qsljpcaa foreign key (quest_id) references quest;
alter table if exists page_game add constraint FKidnqojap81nbb7x6oxo310h5t foreign key (game_id) references game;
alter table if exists team add constraint FKiuc1enrscnuvk6enp59rbfme foreign key (quest_id) references quest;
alter table if exists user_role add constraint FKfpm8swft53ulq2hl11yplpr5 foreign key (user_id) references usr;